const fs=require('fs');
function read(p){if(!fs.existsSync(p))throw new Error(`missing ${p}`);return fs.readFileSync(p,'utf8')}
function need(src,token,label){if(!src.includes(token))throw new Error(`document vault advanced check failed: ${label}`)}
const advanced=read('web/document-vault-advanced-runtime.js');
const offline=read('web/document-vault-offline-ocr-runtime.js');
const encrypted=read('web/document-vault-encrypted-runtime.js');
const encryptedHard=read('web/encrypted-vault-hardening-runtime.js');
const loader=read('web/productivity-tools-runtime.js');
const startup=read('web/device-name-runtime.js');
const assets=read('scripts/prepare-android-assets.mjs');
new Function(advanced);new Function(offline);new Function(encrypted);new Function(encryptedHard);new Function(startup);
need(loader,'document-vault-advanced-runtime.js','advanced vault runtime loader');
need(loader,'document-vault-offline-ocr-runtime.js','offline OCR runtime loader');
need(loader,'document-vault-encrypted-runtime.js','encrypted vault runtime loader');
need(startup,'encrypted-vault-hardening-runtime.js','encrypted vault hardening startup loader');
need(advanced,'تحرير متقدم','advanced editor entry');
need(advanced,'قص حر','direct free crop');
need(advanced,'منظور 4 زوايا','four-corner perspective');
need(advanced,'function bindCrop','direct crop gesture binding');
need(advanced,'function bindPerspective','perspective gesture binding');
need(advanced,'avaSharpen','sharpen control');
need(advanced,'avaDenoise','denoise control');
need(advanced,'avaTemp','white balance temperature control');
need(advanced,'avaSaturation','saturation control');
need(advanced,'function homography','true projective homography');
need(advanced,'MAX_SOURCE_PIXELS','source memory guard');
need(advanced,'MAX_OUTPUT_PIXELS','output memory guard');
need(advanced,"syncState='pending'",'edited image must re-enter sync queue');
need(offline,"createWorker('ara+eng'",'Arabic and English OCR');
need(offline,"workerPath:'vendor/tesseract/worker.min.js'",'local OCR worker');
need(offline,"langPath:'vendor/tesseract/lang'",'local OCR languages');
need(offline,"corePath:'vendor/tesseract/core'",'local OCR core');
need(offline,'async function terminate()','OCR worker termination');
need(offline,'scheduleIdle(15000)','OCR release after app background');
need(offline,'scheduleIdle()','OCR release after recognition');
need(assets,'tesseract.js@5.1.1/dist/tesseract.min.js','pinned Tesseract browser bundle');
need(assets,'tesseract.js-core@5.1.1','pinned Tesseract core');
need(assets,'ara.traineddata.gz','Arabic trained data');
need(assets,'eng.traineddata.gz','English trained data');
need(assets,'Offline OCR assets (Arabic + English) are embedded','offline OCR packaging confirmation');
need(encrypted,"AES-GCM",'AES-GCM encrypted private vault');
need(encrypted,"PBKDF2",'password based key derivation');
need(encrypted,'250000','PBKDF2 work factor');
need(encrypted,'الخزنة الخاصة المشفرة','encrypted vault UI');
need(encrypted,"visibilityState==='hidden'",'clear vault key when app is hidden');
need(encrypted,'key=null','vault key must be memory-only and lockable');
for(const token of ['__ABU_ENCRYPTED_VAULT_HARDENING_V1__','12 محرفًا','failures>=5','lockedUntil','ABUEV1','نسخة مشفرة للخزنة','استعادة الخزنة الخاصة','sessionPass=\'\''])need(encryptedHard,token,'encrypted vault hardening '+token);
console.log('document vault advanced checks passed: image editor, offline OCR with idle release, encrypted vault strong-password gate, lock-on-close, and independent encrypted recovery backup');
