const fs=require('fs'),vm=require('vm');
const read=p=>{if(!fs.existsSync(p))throw new Error('missing '+p);return fs.readFileSync(p,'utf8')};
const need=(s,t,l)=>{if(!s.includes(t))throw new Error('app update check failed: '+l)};
const forbid=(s,t,l)=>{if(s.includes(t))throw new Error('app update check failed: forbidden '+l)};
const runtime=read('web/app-update-runtime.js');
const loader=read('web/device-name-runtime.js');
const edge=read('supabase/functions/app-update/index.ts');
const migration=read('supabase/migrations/20260926215416_app_release_update_center.sql');
const publishMigration=read('supabase/migrations/202609270001_app_release_publish_rpc.sql');
const publisherGuard=read('supabase/migrations/202609270002_app_release_publisher_guard.sql');
const signingBaseline=read('supabase/migrations/202609270003_release_signing_baseline.sql');
const pinnedCertificate=read('config/release-signing-certificate.sha256').trim().toLowerCase();
const publisher=read('scripts/publish-app-update.mjs');
const pkg=JSON.parse(read('package.json'));
new vm.Script(runtime,{filename:'app-update-runtime.js'});new vm.Script(loader,{filename:'device-name-runtime.js'});
if(!/^[0-9a-f]{64}$/.test(pinnedCertificate))throw new Error('app update check failed: pinned production signing fingerprint is invalid');
for(const m of ['__ABU_APP_UPDATE_V1__','current_code','Authorization','download_ready','validDownloadUrl','dlbxcqkbmvnrcrbhuttv.supabase.co','Android.openExternal','لا يحتوي التطبيق على GitHub Token'])need(runtime,m,m);
for(const m of ['loadAppUpdate','app-update-runtime.js','__ABU_APP_UPDATE_V1__','setTimeout(loadAppUpdate,240)'])need(loader,m,'loader '+m);
for(const m of ['npm:@supabase/supabase-js@2.58.0','auth.getUser()','abu_bassam_app_releases',".eq('channel','stable')",".eq('active',true)",'available&&release.storage_path&&release.sha256&&release.signing_cert_sha256','createSignedUrl','Cache-Control','no-store'])need(edge,m,'edge '+m);
for(const m of ['enable row level security','as restrictive','using (false)','with check (false)','revoke all on table public.abu_bassam_app_releases from public, anon, authenticated','grant select on table public.abu_bassam_app_releases to service_role','abu_bassam_app_releases_one_active_channel'])need(migration,m,'migration '+m);
for(const m of ['abu_bassam_publish_app_release','security definer','set search_path = public, pg_temp','INVALID_RELEASE_STORAGE_PATH','INVALID_RELEASE_SHA256','INVALID_RELEASE_CERTIFICATE',"storage_bucket,storage_path,sha256,signing_cert_sha256",'revoke all on function public.abu_bassam_publish_app_release','from public, anon, authenticated','grant execute on function public.abu_bassam_publish_app_release','to service_role'])need(publishMigration,m,'publisher migration '+m);
for(const m of ['storage.objects',"bucket_id='abu-bassam-private'",'RELEASE_APK_NOT_FOUND','RELEASE_DOWNGRADE_NOT_ALLOWED','SIGNING_CERTIFICATE_MISMATCH','for update',"replace(lower(coalesce(v_previous.signing_cert_sha256,'')),':','')",'revoke all on function public.abu_bassam_publish_app_release','to service_role'])need(publisherGuard,m,'publisher guard '+m);
need(signingBaseline,pinnedCertificate,'signing baseline migration must match pinned fingerprint');
for(const m of ['release-signing-certificate.sha256','signed-production-release-with-embedded-js','SUPABASE_SERVICE_ROLE_KEY','APK SHA-256 does not match dist/SHA256.txt','certificate SHA-256 digest','Production signing certificate mismatch','app-releases/${v}/${apkName}','abu-bassam-private','x-upsert','/storage/v1/object/authenticated/','Stored APK size mismatch','Stored APK SHA-256 mismatch','abu_bassam_publish_app_release','p_signing_cert_sha256','p_min_supported_code'])need(publisher,m,'publisher '+m);
if(pkg.scripts?.['publish:update']!=='node scripts/publish-app-update.mjs')throw new Error('app update check failed: package publish:update command missing');
forbid(runtime,'github.com','GitHub download URL in client');
forbid(runtime,'ghp_','GitHub personal access token');
forbid(edge,'verify_jwt = false','unauthenticated update gateway');
forbid(publisher,'console.log(serviceKey)','publisher must never print service role key');
console.log('app update checks passed: authenticated metadata gateway, integrity metadata required before download, service-role-only publication, verified APK existence, pinned production signing certificate continuity and downgrade prevention, production-build/hash/certificate checks before upload, post-upload size/SHA-256 verification, private Storage, signed short-lived URL, and no GitHub token in the APK source.');
