const fs=require('fs'),vm=require('vm');
function read(p){if(!fs.existsSync(p))throw new Error(`missing ${p}`);return fs.readFileSync(p,'utf8')}
function need(src,token,label){if(!src.includes(token))throw new Error(`cards check failed: ${label}`)}
const loader=read('web/productivity-tools-runtime.js');
const upgrades=read('web/cards-section-upgrades-runtime.js');
const plus=read('web/card-models-plus-runtime.js');
const standalone=read('web/standalone-card-layouts-plus-runtime.js');
const a4=read('web/a4-card-sheet-editor-v2-runtime.js');
const freeLayout=read('web/card-free-layout-runtime.js');
const hardening=read('web/cards-hardening-runtime.js');
const hardeningFixes=read('web/cards-hardening-fixes-runtime.js');
const envelopePreload=read('web/envelope-preload-runtime.js');
const library=read('web/card-template-library.js');
const catalog=read('web/card-templates-v2.html');
const student=read('web/student-thanks-cards.html');
const standaloneBase=read('web/standalone-card-models-runtime.js');
for(const src of [upgrades,plus,standalone,a4,freeLayout,standaloneBase,hardening,hardeningFixes,envelopePreload])new Function(src);
const sandbox={window:{}};vm.runInNewContext(library,sandbox);const groups=sandbox.window.AbuBassamCardTemplateLibrary;if(!Array.isArray(groups))throw new Error('cards check failed: template library did not load');
const expected={personal:5,child:10,login:10,wifi:3,qr:4,ration:10,mawkib:4,'student-thanks':10,envelope:9,certificate:10,thanks:6};
for(const [id,n] of Object.entries(expected)){const g=groups.find(x=>x.id===id);if(!g)throw new Error(`cards check failed: missing group ${id}`);if(g.models.length!==n)throw new Error(`cards check failed: ${id} must contain exactly ${n} approved models, found ${g.models.length}`)}
for(const f of ['card-models-plus-runtime.js','cards-section-upgrades-runtime.js','standalone-card-layouts-plus-runtime.js'])need(loader,f,`loader ${f}`);
need(loader,'card-free-layout-runtime.js','free card layout runtime must be loaded');
need(upgrades,'cards-hardening-runtime.js','cards hardening runtime must be loaded');
need(upgrades,'cards-hardening-fixes-runtime.js','final cards guard fixes must be loaded');
need(upgrades,'a4-card-sheet-editor-v2-runtime.js','refined A4 editor must be loaded after base hooks');
need(upgrades,'data-field="line"','child transport line must be cleared/removed');
need(upgrades,'قراءة من الاستديو','gallery barcode button');
need(upgrades,'.cs-login-value .cs-cap','uppercase letters red in login card');
need(upgrades,'student-thanks-cards.html','student thanks section route');
need(upgrades,'card-models-runtime.js','base card model dependency');
need(upgrades,'prepareA4Html','A4 HTML must be sanitized before free sheet editing');
need(upgrades,'abuBassamCardFreeLayoutV1','free card element layout must survive A4 printing');
need(freeLayout,'تحرير الباج','explicit card edit mode checkbox');
need(freeLayout,'abuBassamCardEditModeV1','card edit mode persistence');
need(freeLayout,'if(!editMode)return','elements must not move when edit mode is off');
need(freeLayout,'AbuBassamCardFreeLayout','card edit mode public API');
for(let i=1;i<=5;i++)need(library,`personal-${i}`,`personal model ${i}`);
for(let i=1;i<=10;i++)need(library,`login-${i}`,`login model ${i}`);
for(let i=1;i<=9;i++)need(library,`env-${i}`,`envelope model ${i}`);
for(const id of ['child-clouds','child-future','wifi-3','qr-4'])need(library,id,`catalog model ${id}`);
need(library,"id:'thanks'",'thanks section exists');
for(let i=1;i<=10;i++)need(standaloneBase,`'t${i}'`,`standalone ration model t${i}`);
need(standaloneBase,'student-thanks-cards.html','student template hash routing');
need(standalone,'card.t10','distinct ration layout t10');
need(standalone,'abuMawkibOutput','mawkib A4/CR80 selector');
need(a4,'a4v2-count','A4 copy stepper');
need(a4,"DIRS=['nw','n','ne','e','se','s','sw','w']",'eight A4 resize handles');
need(a4,'function rotate','A4 rotation handle');
need(a4,'function copies','A4 quantity duplication');
need(a4,'function isA4','A4-only editor guard');
need(a4,"page.classList.contains('pair-page')",'A4 pair pages');
need(a4,"querySelectorAll('.pair-card')",'every A4 card must be individually editable');
need(a4,'const snapshots=allPages(doc).map','measure original positions before editor layout');
need(catalog,'model-preview','visual template preview cards');
for(let i=1;i<=10;i++)need(catalog,`.model-preview.v${i}`,`visual preview layout ${i}`);
need(catalog,'preview(g,index)','catalog must render visual preview before selection');
need(library,"id:'student-thanks'",'student thanks catalog section');
for(let i=1;i<=10;i++)need(student,`value="t${i}"`,`student thanks template ${i}`);
need(student,'اسم التلميذ','student name field');need(student,'اسم المعلم','teacher field');need(student,'مدير المدرسة','principal field');
need(hardening,"['printNow','cardsPrint']",'CardsStudio print permission guard');
need(hardening,"['savePdf','cardsExportPdf']",'CardsStudio PDF permission guard');
need(hardening,"['exportPng','cardsExportImage']",'CardsStudio image permission guard');
need(hardening,"['setTextStyle','cardsEditText']",'CardsStudio text edit permission guard');
need(hardening,"['pickPhoto','cardsImportImage']",'CardsStudio image import permission guard');
need(hardening,"['copyCard','cardsDuplicate']",'CardsStudio duplicate permission guard');
need(hardening,"Android.__abuCardsHardBridge",'native bridge must be permission guarded while recovery card tool is open');
need(hardening,"abuDesignPrint:'cardsPrint'",'design-studio iframe print messages must be guarded');
need(hardening,'abuStandaloneEditorBar','standalone cards must expose real layout editor');
need(hardening,'data-text','standalone text editing');
need(hardening,'data-delete','standalone element deletion');
need(hardening,'abu-se-handle','standalone element resize handle');
need(hardening,'abu-se-rot','standalone element rotation handle');
need(hardening,'07829667521','standalone branded footer phone');
need(hardeningFixes,"mode.startsWith('a4')",'A4 layout permission must be enforced');
need(hardeningFixes,"mode==='cr80'",'direct CR80 permission must be enforced');
need(hardeningFixes,'safeTextTarget','standalone text edits must preserve editor controls');
need(hardeningFixes,'isCardA4','native A4 bridge must not bypass cardsA4Layout');
console.log('cards section hardening checks passed');
