const fs=require('fs');
function read(p){if(!fs.existsSync(p))throw new Error(`missing ${p}`);return fs.readFileSync(p,'utf8')}
function need(src,token,label){if(!src.includes(token))throw new Error(`notification check failed: ${label}`)}
function forbid(src,token,label){if(src.includes(token))throw new Error(`notification check failed: ${label}`)}
const runtime=read('web/notification-center-runtime.js');
const corrections=read('web/notification-center-corrections-runtime.js');
const bridge=read('web/notification-ops-bridge-runtime.js');
const privacy=read('web/operation-log-privacy-runtime.js');
const secondaryPrivacy=read('web/secondary-notification-privacy-runtime.js');
const loader=read('web/productivity-tools-runtime.js');
const startupLoader=read('web/device-name-runtime.js');
const migration=read('supabase/migrations/202609240002_notification_audit_center.sql');
const privacyMigration=read('supabase/migrations/202609240003_operation_log_privacy_boundary.sql');
const redactionMigration=read('supabase/migrations/202609240012_notification_audit_server_redaction.sql');
new Function(runtime);new Function(corrections);new Function(bridge);new Function(privacy);new Function(secondaryPrivacy);new Function(startupLoader);
need(loader,'operation-log-privacy-runtime.js','operation privacy runtime is not loaded');
need(loader,'notification-center-runtime.js','notification runtime is not loaded');
need(loader,'notification-ops-bridge-runtime.js','stable operations bridge is not loaded');
need(startupLoader,'notification-center-corrections-runtime.js','notification corrections must load during app startup');
need(startupLoader,'loadNotificationCorrections()','startup must invoke notification corrections');
need(bridge,'secondary-notification-privacy-runtime.js','secondary notification privacy runtime is not loaded by the bridge');
need(bridge,'notification-center-corrections-runtime.js','notification corrections runtime is not loaded by the bridge');
need(bridge,'script.async=false','notification privacy/corrections must preserve load order');
need(bridge,'rootOriginal','bridge must unwrap temporary notification wrappers');
need(bridge,'__abuOriginal','bridge must retain the raw operation writer');
need(bridge,'ops.list?.()?.[0]','bridge must read the persisted operation id');
need(bridge,'abuBassamOperationDeviceScopeV1','operation ownership map');
need(bridge,'bindOperationToDevice','new operations must be bound to their originating device');
need(bridge,'attempts>50','bridge must survive startup wrapper races');
need(privacy,"!=='operation'",'legacy operation cloud traffic must be intercepted');
need(privacy,"role()!=='secondary'",'secondary local log isolation');
need(privacy,'ownerId===id','secondary logs must be filtered by exact device id');
need(privacy,'abuBassamOperationDeviceScopeV1','secondary logs must use the ownership map');
need(privacy,'delayedClean','startup/online sync race must be cleaned repeatedly');
forbid(privacy,'deviceName()','secondary isolation must not fall back to device name');
need(secondaryPrivacy,"role()!=='secondary'",'secondary notification inbox must be isolated');
need(secondaryPrivacy,'ownerId===id','operation notifications must match exact device id');
need(secondaryPrivacy,'return !!nDevice&&nDevice===id','non-operation notifications must require exact device id');
need(secondaryPrivacy,"notification.source==='branch-audit'",'branch audit rows must never appear in a secondary inbox');
need(secondaryPrivacy,'abuBassamOperationDeviceScopeV1','notification privacy must use the ownership map');
need(secondaryPrivacy,'abuBassamAuditQueueV1','secondary audit queue must be privacy filtered');
need(secondaryPrivacy,'ownQueue','foreign queued audit events must be purged before upload');
need(runtime,'abuNotificationBell','bell button');
need(runtime,'abuNotificationBadge','unread badge');
need(runtime,'markAll','mark all read');
need(runtime,'clearRead','clear read notifications');
for(const token of ["['all','الكل']","['unread','غير المقروء']","['print','الطباعة']","['files','الملفات']","['security','الأمان']","['sync','المزامنة']","['settings','الإعدادات']","['cards','الكروت']","['system','النظام']"]) need(runtime,token,`category ${token}`);
need(runtime,'abu_bassam_owner_activity_report','owner-only report RPC');
need(runtime,'abu_bassam_record_device_activity','verified activity RPC');
need(runtime,"exportAdmin('csv')",'CSV report export');
need(runtime,"exportAdmin('txt')",'TXT report export');
need(runtime,"exportAdmin('pdf')",'PDF report export');
for(const token of ['__ABU_NOTIFICATION_CENTER_CORRECTIONS_V2__','validOps.has(opId)','sameOperation(a,b)','isPhantomOperation','seen.has(n.id)','[هاتف محجوب]','[بريد محجوب]','[تفاصيل زبون محجوبة]','هذا إشعار حرج','تقارير الأجهزة الفرعية','String(scope[id]||\'\').trim()!==d.id'])need(corrections,token,`notification corrections ${token}`);
need(migration,'revoke all on public.abu_bassam_device_activity from anon,authenticated','direct table access revoked');
need(migration,'from PUBLIC,anon','security-definer PUBLIC/anon execution revoked');
need(migration,"v_actor.role<>'owner'",'server owner verification');
need(migration,'DEVICE_NOT_AUTHORIZED','device secret verification');
need(migration,'abu_bassam_owner_activity_devices','owner device report RPC');
need(privacyMigration,"kind <> 'operation'",'legacy operation rows excluded by RLS');
for(const token of ["coalesce(v_device.secret_hash,'')=''",'v_device.secret_hash<>v_hash','[تفاصيل زبون محجوبة]','[هاتف محجوب]','[بريد محجوب]','[رقم محجوب]','revoke all on function public.abu_bassam_record_device_activity'])need(redactionMigration,token,`server audit redaction ${token}`);
console.log('notification center checks passed: early privacy startup, exact secondary isolation, stable operation ids, safe duplicate cleanup without deleting history, critical-delete confirmation, client/server PII redaction, and owner-only reports');
