const fs=require('fs');
function read(p){if(!fs.existsSync(p))throw new Error(`missing ${p}`);return fs.readFileSync(p,'utf8')}
function need(src,t,label){if(!src.includes(t))throw new Error(`customer documents check failed: ${label}`)}
function forbid(src,t,label){if(src.includes(t))throw new Error(`customer documents check failed: forbidden ${label}`)}
const ui=read('web/customer-documents-runtime.js');
const workflow=read('web/customer-documents-workflow-runtime.js');
const hard=read('web/customer-permissions-hardening-runtime.js');
const quality=read('web/customer-image-quality-runtime.js');
const frame=read('web/customer-camera-frame-runtime.js');
const loader=read('web/device-name-runtime.js');
const native=read('index.js');
const migration=read('supabase/migrations/202609240004_customer_documents.sql');
const workflowMigration=read('supabase/migrations/202609240005_customer_documents_workflow.sql');
const atomicMigration=read('supabase/migrations/202609240010_atomic_customer_document_revisions.sql');
const permissionMigration=read('supabase/migrations/202609250004_customer_permissions_enforcement.sql');
const edge=read('supabase/functions/customer-documents/index.ts');
new Function(ui);new Function(workflow);new Function(hard);new Function(quality);new Function(frame);
need(loader,'customer-permissions-hardening-runtime.js','permission hardening loader');
need(ui,'مستمسكات الزبائن','customer documents center');
need(ui,'كل فرع مستقل تمامًا','branch isolation notice');
need(ui,"p_device_secret",'device secret required');
need(ui,"role()==='owner'",'owner-only cross-branch UI');
need(ui,"national_front",'national ID front');
need(ui,"national_back",'national ID back');
need(ui,"residence_front",'residence front');
need(ui,"residence_back",'residence back');
need(ui,"personal_photo",'personal photo');
need(ui,"مستمسكات الزوجة",'spouse documents');
need(ui,"مستمسكات طفل",'children documents');
need(ui,"appointment_order",'appointment orders');
need(ui,"admin_letter",'administrative letters');
need(ui,"الكاميرا الذكية",'smart camera entry');
need(ui,"تحرير/الوطنية",'send to national ID editor');
need(ui,"دمج A4",'A4 merge');
need(frame,"frameKind",'camera frame selector');
need(native,"cardDocumentFrame",'ID-card live camera frame in authoritative native source');
need(native,"photoDocumentFrame",'portrait live camera frame in authoritative native source');
need(native,"message.frameKind",'native bridge frame kind in authoritative native source');
need(native,"cameraFrameKind",'native camera frame state');
need(workflow,"abu_bassam_customer_list_v2",'enhanced customer search source');
need(workflow,"size_desc",'sort by size');
need(workflow,"time_desc",'sort by time');
need(workflow,"alpha_asc",'alphabetic sort');
need(workflow,"branch",'branch sort');
need(workflow,"thumbs",'thumbnail view');
need(workflow,"names",'names-only view');
need(workflow,"قائمة تفصيلية",'detailed list view');
need(workflow,"ملاحظات الزبون",'customer note at top');
need(workflow,"cwfSharp",'sharpen image editor');
need(workflow,"cwfNoise",'denoise image editor');
need(workflow,"cwfBright",'brightness image editor');
need(workflow,"cwfContrast",'contrast image editor');
need(workflow,"cwfTemp",'temperature image editor');
need(workflow,"cwfCrop",'touch crop editor');
need(workflow,"original_file",'private original image preservation');
need(workflow,"download(id,'original')",'restore/re-edit original');
need(workflow,"2x1",'2x1 merge template');
need(workflow,"2x2",'2x2 merge template');
need(workflow,"2x3",'2x3 merge template');
need(workflow,"3x2",'3x2 merge template');
need(workflow,"علامة مائية",'merge watermark');
need(quality,"الصورة مظلمة",'automatic darkness warning');
need(quality,"التباين منخفض",'automatic contrast warning');
need(quality,"التفاصيل/الوضوح منخفض",'automatic sharpness warning');
need(workflowMigration,"total_size_bytes",'customer total size metadata');
need(workflowMigration,"original_storage_path",'original image metadata');
need(atomicMigration,"abu_bassam_customer_document_upload_plan",'atomic upload plan');
need(atomicMigration,"abu_bassam_customer_document_commit_v3",'atomic revision commit');
need(migration,'revoke all on public.abu_bassam_customers from anon,authenticated','no direct customer table reads');
need(migration,'revoke all on public.abu_bassam_customer_documents from anon,authenticated','no direct document table reads');
need(migration,"'abu-bassam-customers-private'",'private customer bucket');
need(permissionMigration,"'customerAdd'",'server customer add permission');
need(permissionMigration,"'customerEdit'",'server customer edit permission');
need(permissionMigration,"'customerDelete'",'server customer delete permission');
need(permissionMigration,"'customerPhoneView'",'server phone redaction permission');
need(permissionMigration,"'customerSensitiveDataView'",'server sensitive-data redaction permission');
need(permissionMigration,"'customerDocumentsView'",'server document view permission');
need(permissionMigration,"'customerDocumentsAdd'",'server document add permission');
need(permissionMigration,"'customerDocumentsEdit'",'server document edit permission');
need(permissionMigration,"'customerDocumentsDelete'",'server document delete permission');
need(permissionMigration,"abu_bassam_customer_delete",'customer delete RPC');
need(permissionMigration,"jsonb_object_keys(p_permissions)",'portable permission count');
forbid(permissionMigration,'jsonb_object_length(p_permissions)','unsupported jsonb_object_length');
need(edge,"SUPABASE_SERVICE_ROLE_KEY",'server-only file gateway');
need(edge,"x-device-id",'edge device identity');
need(edge,"x-device-secret",'edge device secret');
need(edge,"defaultValue=false",'fail-closed granular permissions');
need(edge,"action==='delete-customer'",'customer delete storage cleanup');
need(edge,"abu_bassam_customer_delete",'customer delete RPC edge call');
need(edge,"customerDocumentsDelete",'document delete edge permission');
need(edge,"customerOriginalDocumentView",'original image view permission');
need(edge,"abu_bassam_customer_document_commit_v3",'atomic edge commit');
need(hard,"abu_bassam_owner_devices",'safe owner branch list');
need(hard,"abu_bassam_customer_transfer",'safe branch transfer');
need(hard,"delete-customer",'customer delete UI action');
need(hard,"custDeleteCustomerHard",'customer delete button');
forbid(hard,".from('abu_bassam_devices')",'direct device table read in hardening runtime');
forbid(workflow,'سلة محذوفات','recycle bin');
console.log('customer documents, permissions, deletion, atomic revisions and branch isolation checks passed');
