const fs=require('fs');
function read(p){if(!fs.existsSync(p))throw new Error(`missing ${p}`);return fs.readFileSync(p,'utf8')}
function need(src,token,label){if(!src.includes(token))throw new Error(`cards latest hardening failed: ${label}`)}
function reject(src,token,label){if(src.includes(token))throw new Error(`cards latest hardening failed: ${label}`)}
const fixes=read('web/cards-hardening-fixes-runtime.js');
const hard=read('web/cards-hardening-runtime.js');
const upgrades=read('web/cards-section-upgrades-runtime.js');
const finalAudit=read('web/cards-final-audit-runtime.js');
const envelopePreload=read('web/envelope-preload-runtime.js');
const plus=read('web/card-models-plus-runtime.js');
new Function(fixes);new Function(hard);new Function(upgrades);new Function(finalAudit);new Function(envelopePreload);new Function(plus);
need(upgrades,'cards-hardening-fixes-runtime.js','latest hardening runtime is not loaded');
need(upgrades,'__ABU_CARDS_HARDENING_FIXES_V2__','loader must target V2 hardening guard');
need(upgrades,'cards-final-audit-runtime.js','final card audit runtime must be loaded');
need(upgrades,'__ABU_CARDS_FINAL_AUDIT_V1__','final card audit guard must be loaded');
need(upgrades,'__abuCardsBootstrap','card permissions need a fail-closed bootstrap facade');
need(upgrades,"can(){try{return window.AbuBassamSecurity?.role?.()==='owner'}",'bootstrap may only allow owner before full permissions load');
need(upgrades,"cardsBarcode')!==true",'gallery barcode shortcut must enforce cardsBarcode');
need(upgrades,"guardChild(win,'resetCard',['cardsCreate','cardsEdit']",'ration new/reset action must require create and edit permissions');
need(upgrades,"guardChild(win,'resetForm',['cardsCreate','cardsEdit']",'standalone new/reset form action must require create and edit permissions');
need(upgrades,"guardChild(win,'resetLetter',['cardsCreate','cardsEdit']",'thanks-letter new action must require create and edit permissions');
need(upgrades,"guardChild(win,'saveImages',['cardsExportImage','imageExport','exportOutsideApp']",'standalone gallery image export must enforce export permissions');
need(upgrades,'Android.savePagesToGallery','multi-image native gallery bridge must be guarded');
need(upgrades,'__abuCardsGalleryGuard','multi-image gallery guard marker is missing');
need(upgrades,"guardChild(win,'printNow',['cardsPrint','printCards','printGeneral']",'student thanks direct print action must be guarded');
need(finalAudit,'07829667521','standalone front/back brand footer must include the library phone');
need(finalAudit,"['ration-card.html','mawkib-cards.html']",'CR80 standalone branding targets must be explicit');
need(finalAudit,'.abu-brand-footer','front-side standalone brand footer is missing');
need(finalAudit,'تصميم: أكرم حاتم الغزالي','approved designer identity must be applied to designs');
need(finalAudit,"@media print{.designer{display:block!important}}",'approved designer identity must remain visible in print/PDF');
need(finalAudit,"guardChild(win,'saveImages',['cardsExportImage','imageExport','exportOutsideApp']",'final audit must guard direct multi-image export');
need(finalAudit,'Android.savePagesToGallery','final audit must guard gallery bridge');
need(fixes,'__ABU_CARDS_HARDENING_FIXES_V2__','V2 final card hardening guard');
need(fixes,"window.AbuBassamPermissions.can(k)===true",'branch permission checks must fail closed');
need(fixes,'reapplyOverrides','text/image overrides must survive rerender');
need(fixes,"b.dataset.image='1'",'standalone image replacement button is missing');
need(fixes,"['cardsEdit','cardsEditImage']",'image replacement must require edit and image permissions');
need(fixes,"['cardsEdit','cardsEditText']",'text editing must require edit and text permissions');
need(fixes,'cardsManageCustomTemplates','custom template management permission is not enforced');
need(fixes,'cardsTemplatesEdit','template edit/select permission is not enforced');
need(fixes,'refreshStandaloneTemplateState','standalone edits must be rebound when the template changes');
need(fixes,'const idx=index++','standalone element indexing must match the base editor key order');
need(fixes,"[file,template,frameSide(el),el.id||('e'+idx)]",'standalone layout key must include the active template');
need(fixes,'scheduleCleanTemplateReload','static template changes must reload once from a clean DOM');
need(fixes,'abuCardsTemplateReload:','template reload loop guard is missing');
need(fixes,'doc.__abuTemplateSwitching=true','template switching must suppress stale override reapplication');
need(fixes,'clearPreviousOverride','old template geometry must be removed before applying the new template');
need(fixes,'printKeys','printing must use an action-specific permission set');
need(fixes,'pdfKeys','PDF export must use an action-specific permission set');
need(fixes,"mode==='cr80'",'direct CR80 printing permission guard is missing');
need(fixes,'isCardCr80','standalone CR80 output must be detected');
need(fixes,'isCardA4','A4 output must be detected');
need(fixes,'patchReactNativeBridge','ReactNativeWebView direct output bypass must be guarded');
need(fixes,'__abuCardsFinalBridgeGuard','bridge wrappers must be function-level and re-wrappable');
need(fixes,'#csForm [data-field]','main card data fields must become read-only when editing is denied');
need(fixes,'csBarcodeImageInput','barcode file input must be disabled when barcode permission is denied');
need(fixes,'#dsCanvas [contenteditable]','design studio direct text editing must be guarded');
need(fixes,'#dsCanvas .ds-el','design studio pointer editing must be guarded');
need(fixes,"cardsA4Layout','printA4",'A4 print must require both card layout and print A4 permissions');
need(fixes,"cardsExportPdf','pdfCreate','pdfSave",'PDF export must require PDF permissions');
need(fixes,"cardsPrint','printCards','printGeneral",'card printing must require card and global print permissions');
need(envelopePreload,"item.id==='env-10'",'legacy env-10 cleanup is missing');
reject(envelopePreload,"id:'env-10'",'obsolete env-10 template is still being injected');
need(envelopePreload,"state.templateId==='env-10'",'saved obsolete env-10 state must be detected');
need(envelopePreload,"state.templateId='env-1'",'saved obsolete env-10 state must migrate to env-1');
reject(fixes,'env-10','obsolete env-10 protection remains in final fixes runtime');
reject(hard,'env-10','obsolete env-10 promotion remains in hardening runtime');
need(plus,'__ABU_CARD_MODELS_PLUS_RETIRED__','obsolete extra-card injector must stay retired');
reject(plus,"personal-6','personal-7",'obsolete personal models are still exposed');
reject(fixes,"const can=k=>window.AbuBassamPermissions?.can?.(k)!==false",'fail-open permission helper returned');
console.log('latest cards hardening checks passed');
