const fs=require('fs'),vm=require('vm');
const read=p=>{if(!fs.existsSync(p))throw new Error('missing '+p);return fs.readFileSync(p,'utf8')};
const runtime=read('web/admin-permissions-runtime.js');
const guards=read('web/permission-section-guards-runtime.js');
const loader=read('web/device-name-runtime.js');
const baseMigration=read('supabase/migrations/202609250001_advanced_admin_permissions.sql');
const retireMigration=read('supabase/migrations/202609290001_retire_removed_section_permissions.sql');
const helper=read('supabase/migrations/202609250002_customer_permission_helper.sql');
const capacity=read('supabase/migrations/202609250003_advanced_permissions_capacity.sql');
const edge=read('supabase/functions/customer-documents/index.ts');
new vm.Script(runtime,{filename:'admin-permissions-runtime.js'});new vm.Script(guards,{filename:'permission-section-guards-runtime.js'});new vm.Script(loader,{filename:'device-name-runtime.js'});
const items=[...runtime.matchAll(/\['([A-Za-z][A-Za-z0-9]+)','[^'\n]*',(true|false)\]/g)].map(m=>m[1]);
const unique=[...new Set(items)];
if(items.length<150)throw new Error(`permission catalog unexpectedly small (${items.length})`);
if(unique.length!==items.length)throw new Error('duplicate detailed permission keys');
const retired=['questionsView','questionsCreate','questionsEdit','questionsDelete','questionsTemplates','questionsCustomTemplates','questionsAnswersToggle','questionsImages','questionsPrint','questionsPdf','questionsReset','questionsMaintenance','compressUse','compressBatch','compressSave','compressExport','compressHighResolution','compressDeleteOriginal','printQuestions'];
for(const key of retired){if(runtime.includes(key))throw new Error(`retired runtime permission remains: ${key}`);if(guards.includes(key))throw new Error(`retired guard permission remains: ${key}`);if(!retireMigration.includes(`- '${key}'`))throw new Error(`retirement migration does not scrub ${key}`)}
for(const key of unique)if(!retireMigration.includes(`'${key}'`))throw new Error(`current server catalog missing ${key}`);
for(const key of ['edit','print','export','appearance','sync','security','devices','reset'])if(!retireMigration.includes(`'${key}'`))throw new Error(`legacy compatibility missing ${key}`);
for(const marker of ['__ABU_ADMIN_PERMISSIONS_V1__','صلاحيات متقدمة','السماح للكل','منع الكل','قراءة فقط','موظف طباعة','موظف مستمسكات','موظف تصميم','مخصص / الحالي','vaultView','customerDocumentsView','cardsEdit','printGeneral','pdfSave','syncAutomatic','logsViewOwn','notificationsView','securityView','settingsView','adminViewAllBranches','ADMIN_ONLY','saveDevicePermissions','abu_bassam_manage_device','AbuBassamPermissions'])if(!runtime.includes(marker))throw new Error(`admin runtime missing ${marker}`);
for(const marker of ['__ABU_PERMISSION_SECTION_GUARDS_V2__','logsViewOwn','notificationsView','securityBiometric','securityAutoLock','securityPrivacyMode','syncAutomatic','printGeneral','pdfSave','imageExport','cardsPrint','customerPhoneView'])if(!guards.includes(marker))throw new Error(`section guards missing ${marker}`);
for(const marker of ['admin-permissions-runtime.js','permission-section-guards-runtime.js','loadAdminPermissions()','loadPermissionSectionGuards()'])if(!loader.includes(marker))throw new Error(`startup loader missing ${marker}`);
for(const marker of ['_abu_bassam_device_permission','secret_hash','p_permission'])if(!helper.includes(marker))throw new Error(`server permission helper missing ${marker}`);
for(const marker of ['customerDocumentsAdd','customerDocumentsEdit','customerDocumentsView','customerOriginalDocumentView','customerDocumentsDelete','sha256Hex','secret_hash'])if(!edge.includes(marker))throw new Error(`customer edge permission missing ${marker}`);
if(!capacity.includes('jsonb_object_length(p_permissions)>260'))throw new Error('server permission payload capacity regression');
const adminBlock=(runtime.match(/const ADMIN_ONLY=new Set\(\[([\s\S]*?)\]\);/)||[])[1]||'';
const adminKeys=[...adminBlock.matchAll(/'([A-Za-z][A-Za-z0-9]+)'/g)].map(m=>m[1]);
if(adminKeys.length<35)throw new Error(`admin-only set too small (${adminKeys.length})`);
for(const key of adminKeys)if(!baseMigration.includes(`'${key}'`))throw new Error(`admin-only server list missing ${key}`);
console.log(`Admin permissions current-state check passed: ${items.length} active detailed permissions, retired section keys scrubbed by forward migration, ${adminKeys.length} admin-only protections.`);
