const fs=require('fs'),vm=require('vm');
const read=p=>{if(!fs.existsSync(p))throw new Error('missing '+p);return fs.readFileSync(p,'utf8')};
const need=(s,t,l)=>{if(!s.includes(t))throw new Error(`branch vault check failed: ${l}`)};
const no=(s,t,l)=>{if(s.includes(t))throw new Error(`branch vault check failed: ${l}`)};
const runtime=read('web/branch-vault-runtime.js');
const hard=read('web/document-vault-hardening-runtime.js');
const guard=read('web/document-vault-permission-guard-runtime.js');
const loader=read('web/device-name-runtime.js');
const migration=read('supabase/migrations/202609240013_branch_private_document_vault.sql');
const edge=read('supabase/functions/branch-vault/index.ts');
new vm.Script(runtime,{filename:'branch-vault-runtime.js'});new vm.Script(hard,{filename:'document-vault-hardening-runtime.js'});new vm.Script(guard,{filename:'document-vault-permission-guard-runtime.js'});new vm.Script(loader,{filename:'device-name-runtime.js'});
for(const t of ['__ABU_BRANCH_VAULT_V1__','vaultView','vaultAdd','vaultEdit','vaultDelete','vaultExport','vaultSync','vaultBackup','abu_bassam_vault_list','abu_bassam_vault_get','abu_bassam_vault_upsert','uploadToSignedUrl','branch-vault','abuBassamVaultLocalScopeV1','الفروع الأخرى لا تستطيع رؤيتها'])need(runtime,t,t);
for(const t of ['AbuBassamSecurity?.device','x-device-id','x-device-secret','VAULT_VIEW_NOT_ALLOWED','VAULT_DELETE_NOT_ALLOWED'])need(runtime,t,'client device-secret enforcement '+t);
for(const t of ['__ABU_DOCUMENT_VAULT_HARDENING_V1__','branchDeviceId','safeSettingKey','MAX_ZIP','MAX_TOTAL','MAX_FILE','ABUVLT1','AES-GCM','PBKDF2','هذه النسخة تخص فرعًا آخر','نسخة مشفرة للفرع'])need(hard,t,'backup hardening '+t);
for(const t of ['__ABU_DOCUMENT_VAULT_PERMISSION_GUARD_V1__','saveActive','shareActive','saveGalleryActive','savePdfActive','printActive','saveEditorGallery','saveEditorPdf','printEditor','shareOcr','saveOcrText','saveOcrPdf','saveOcrWithImage','printOcr','vaultExport','abuVaultViewDenied','shell.style.display=\'none\'','الأدمن عطّل صلاحية عرض ملفات الحفظ لهذا الفرع'])need(guard,t,'permission bypass guard '+t);
for(const t of ['branch-vault-runtime.js','document-vault-hardening-runtime.js','document-vault-permission-guard-runtime.js','loadBranchVault()','loadDocumentVaultHardening()','loadDocumentVaultPermissionGuard()'])need(loader,t,'startup loader '+t);
for(const t of ['abu_bassam_branch_vault','branch_device_id','_abu_bassam_vault_authorized','VAULT_VIEW_NOT_ALLOWED','VAULT_SYNC_NOT_ALLOWED','vaultDelete','kind <> \'vault\'','branch-vault','as restrictive'])need(migration,t,'server isolation '+t);
for(const t of ['SUPABASE_SERVICE_ROLE_KEY','sha256Hex','secret_hash','branch-vault','createSignedUploadUrl','createSignedUrl','VAULT_PATH_INVALID','vaultSync','vaultView','vaultDelete'])need(edge,t,'edge gateway '+t);
no(edge,'service_role"','hardcoded service role');
console.log('branch-private vault checks passed: exact Device ID + Device Secret scope, admin permissions, modal-action guards, full view hiding, no direct vault table/storage path access, signed storage gateway, local scope lock, safe branch-bound restore, and encrypted backup option');