const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const failures=[];
const need=(file,markers)=>{const source=read(file);for(const marker of markers)if(!source.includes(marker))failures.push(`${file}: missing ${marker}`)};
const forbid=(file,markers)=>{const source=read(file);for(const marker of markers)if(source.includes(marker))failures.push(`${file}: forbidden ${marker}`)};

need('index.js',['expo-local-authentication','expo-secure-store','expo-screen-capture','LocalAuthentication.authenticateAsync','SecureStore.setItemAsync','ScreenCapture.preventScreenCaptureAsync','ScreenCapture.allowScreenCaptureAsync',"action === 'privacyMode'",'BackHandler.exitApp','AbuBassamNativeBackPress','AbuBassamNativeAppState','STARTUP_WATCHDOG_MS',"originWhitelist={['file://*','about:*']}",'mixedContentMode="never"','onShouldStartLoadWithRequest']);
forbid('index.js',["originWhitelist={['*']}",'mixedContentMode="always"']);
need('web/app-security-runtime.js',["MAIN_USERNAME='akrama1992'",'abu_bassam_register_device','abu_bassam_manage_device','abu_bassam_remove_device','SECONDARY_DEFAULT','OWNER_PERMISSIONS','toggleBiometric','appearanceSync','اضغط مرة ثانية للخروج']);
need('web/security-hardening-runtime.js',['__ABU_SECURITY_HARDENING_V2__',"SECURE_TRUST_KEY='abu_bassam_offline_trust_v2'","SECRET_KEY='abu_bassam_device_secret_v1'",'OFFLINE_GRACE_MS=7*24*60*60*1000','CLOCK_SKEW_MS=5*60*1000',"name:'HMAC',hash:'SHA-256'","nativeRequest('secureGet',{key:SECRET_KEY})","nativeRequest('secureSet',{key:SECURE_TRUST_KEY","nativeRequest('biometricAuth'",'constantTime(expected,env.mac)','trust?.device_id!==currentId()','trust?.appVersion!==APP_VERSION','now+CLOCK_SKEW_MS<verified','sec.device=effectiveDevice','sec.maxDevices=limit','AbuBassamDeviceRegistry?.readLimit','localStorage.removeItem(LEGACY_TRUST_KEY)','تعذر الوصول إلى طبقة الأمان في Android','offlineSession','lockOffline(','revalidateOfflineSession','abu_bassam_touch_device','setInterval(enforceOfflineSession,60000)']);
need('web/security-extras-runtime.js',['verifyDangerPin','changePassword','abuBassamEmergencySnapshotV1','safeSnapshot','restoreSnapshot',"nativeRequest('privacyMode'",'خصوصية عالية','تسجيل الخروج']);
need('web/password-policy-runtime.js',['__ABU_PASSWORD_POLICY_V1__','v.length<12','\\p{L}','\\p{N}',"c.auth.updateUser({password:next})","c.auth.signOut({scope:'others'})",'extras.changePassword=changePassword']);
need('web/login-throttle-fix-runtime.js',['__ABU_LOGIN_THROTTLE_FIX_V3__','loginBusy','credentialFailure(message)','deviceOrPostAuthFailure(message)','recordCredentialFailure','abu-bassam-auth-ui-ready',"abuThrottleFix==='3'",'وصل الحساب إلى الحد الأقصى']);
need('web/login-input-direction-runtime.js',["setAttribute('dir','ltr')","setAttribute('lang','en')","setAttribute('autocapitalize','off')","setAttribute('spellcheck','false')"]);
need('web/permission-guard-runtime.js',['__ABU_PERMISSION_GUARD_V2__',"return'print'","return'export'","return'appearance'","return'sync'","return'edit'",'abuPermissionDenied','abu-bassam-section-opened','pageshow']);
forbid('web/permission-guard-runtime.js',['stopImmediatePropagation','beforeinput',"document.addEventListener('click'"]);
need('web/device-name-runtime.js',['app-security-runtime.js','security-hardening-runtime.js','loadSecurityHardening()','security-extras-runtime.js','password-policy-runtime.js','permission-guard-runtime.js','login-throttle-fix-runtime.js','login-input-direction-runtime.js','device-reconcile-runtime.js','AbuBassamDeviceRegistry']);
need('web/device-reconcile-runtime.js',['__ABU_DEVICE_RECONCILE_V2__','abu_bassam_owner_devices','abu_bassam_owner_device_count','abu_bassam_set_device_limit','abu_bassam_manage_device','abu_bassam_remove_device','secureGet','refreshLimitUi','sec.renderDevices=render','sec.permissionsDevice=permissionsDevice']);
forbid('web/device-name-runtime.js',["from('abu_bassam_devices')","cloud.list('device')"]);
forbid('web/device-reconcile-runtime.js',["from('abu_bassam_devices')"]);
need('supabase/migrations/202609240006_device_registry_privacy_boundary.sql',['revoke all on table public.abu_bassam_devices from PUBLIC, anon, authenticated','abu_bassam_owner_device_count','abu_bassam_owner_devices',"v_actor.role<>'owner'","v_actor.secret_hash<>v_hash"]);
need('supabase/migrations/202609240007_device_secret_representation.sql',["alter column secret_hash type text",'abu_bassam_devices_secret_hash_valid',"secret_hash ~ '^[0-9a-f]{64}$'",'abu_bassam_remove_device',"v_actor.secret_hash<>v_hash"]);
need('supabase/migrations/202609240008_private_tables_deny_all_and_device_index_cleanup.sql',['drop index if exists public.abu_bassam_devices_user_device_uidx','abu_bassam_devices_deny_select','abu_bassam_customers_deny_select','abu_bassam_customer_documents_deny_select','abu_bassam_device_activity_deny_select','using (false)','with check (false)']);
need('supabase/migrations/202609240009_strict_device_registration_identity.sql',['abu_bassam_devices_one_owner_per_user','pg_advisory_xact_lock',"if v_row.active=false then raise exception 'DEVICE_DISABLED'",'if v_row.secret_hash<>v_hash then raise exception',"v_role:=case when v_count=0 then 'owner' else 'secondary' end"]);
forbid('supabase/migrations/202609240009_strict_device_registration_identity.sql',['lower(trim(coalesce(device_name','active=true where user_id=v_uid and device_id=p_device_id']);

for(const file of ['web/device-name-runtime.js','web/device-reconcile-runtime.js','web/password-policy-runtime.js','web/security-hardening-runtime.js']){try{new Function(read(file))}catch(e){failures.push(`${file}: JavaScript syntax error: ${e.message}`)}}
const packageJson=JSON.parse(read('package.json'));
for(const dep of ['expo-local-authentication','expo-secure-store','expo-screen-capture'])if(!packageJson.dependencies?.[dep])failures.push(`package.json: missing ${dep}`);
const production=['index.js','web/app-security-runtime.js','web/security-hardening-runtime.js','web/security-extras-runtime.js','web/password-policy-runtime.js','web/permission-guard-runtime.js','web/login-throttle-fix-runtime.js','web/device-name-runtime.js','web/device-reconcile-runtime.js'].map(read).join('\n');
for(const marker of [['service','role'].join('_'),['sb','secret',''].join('_'),['BEGIN','PRIVATE','KEY'].join(' ')])if(production.toLowerCase().includes(marker.toLowerCase()))failures.push(`Sensitive server credential marker found in production security source: ${marker}`);
if(failures.length){process.stderr.write(failures.join('\n')+'\n');process.exit(1)}
process.stdout.write('Security/control checks passed: native biometrics and SecureStore, HMAC-sealed 7-day offline trust with background locking and server revalidation, dynamic device limits, strong password changes, private-table deny policies, strict device identity without role inheritance/reactivation, owner-verified device RPCs, guarded permissions, login throttling, LTR credentials, and local-only WebView navigation.\n');
